apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus
  namespace: infra
spec:
  ingressClassName: nginx
  rules:
  - host: sre.choilab.xyz
    http:
      paths:
      - path: /nexus(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: nexus
            port:
              name: http
      - path: /nexus-docker(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: nexus-docker
            port:
              name: docker