apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: nexus
  name: nexus
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: nexus
    namespace: infra
  hostPath:
    path: /mnt/data/nexus
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
