apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 40Gi
  claimRef:
    name: loki
    namespace: infra
  hostPath:
    path: /mnt/data/loki
    