apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-sonarqube-postgresql-0
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage-retain
  hostPath:
    path: /mnt/data/sonarqube
  claimRef:
    name: data-sonarqube-postgresql-0
    namespace: infra
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-sonarqube-postgresql-0
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage-retain
  hostPath:
    path: /mnt/data/sonarqube-data
  claimRef:
    name: data-sonarqube-postgresql-0
    namespace: infra
