apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-storage-retain