apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: postgres
    namespace: infra
  hostPath:
    path: /mnt/data/postgresql
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem