apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    name: grafana
    namespace: infra
  hostPath:
    path: /mnt/data/grafana
    