nodeSelector: 
  role: infra
ingress:
  enabled: true
  ingressClassName: nginx
  path: "/grafana"
  hosts:
      - "sre.choilab.xyz"
  grafana.ini:
    server:
      domain: choilab.xyz
      root_url: "http://sre.choilab.xyz/grafana"
      serve_from_sub_path: true
persistence:
  enabled: true
  type: pvc
  existingClaim: grafana
  finalizers:
      - kubernetes.io/pvc-protection