nodeSelector:
  role: infra
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  ingressClassName: nginx
  path: /grafana(/|$)(.*)
  hosts:
    - "sre.choilab.xyz"
grafana.ini:
  server:
    domain: choilab.xyz
    root_url: http://sre.choilab.xyz/grafana/
    serve_from_sub_path: true
persistence:
  enabled: true
  type: pvc
  existingClaim: grafana
  finalizers:
      - kubernetes.io/pvc-protection