apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins
  namespace: infra
  # annotations:
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: "sre.choilab.xyz/jenkins"
    http:
      paths:
      - backend:
          service:
            name: jenkins
            port:
              number: 8080
        path: /jenkins
        pathType: Prefix