apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  labels:
    type: jenkins
spec:
  # storageClassName: manual
  # persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: jenkins
    namespace: infra
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/jenkins"