kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins
  namespace: infra
  labels:
    type: jenkins
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi