apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-operator-sonarqubecluster-1
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage-retain
  hostPath:
    path: /mnt/data/postgresql-sonarqube
  claimRef:
    name: postgresql-cluster-sonarqube-1
    namespace: infra
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-operator-sonarqubecluster-2
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage-retain
  hostPath:
    path: /mnt/data/postgresql-sonarqube
  claimRef:
    name: postgresql-cluster-sonarqube-2
    namespace: infra
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-operator-sonarqubecluster-3
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage-retain
  hostPath:
    path: /mnt/data/postgresql-sonarqube
  claimRef:
    name: postgresql-cluster-sonarqube-3
    namespace: infra